name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: cedrickring/golang-action@1.3.0
    - name: Run terratest tests
      run: go test -v  -timeout 30m
