name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: cd test && go test
      env:
        AWS_DEFAULT_REGION: "ap-south-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
